// Package pulsight is the official Go client for the Pulsight API.
//
// The generated protocol core lives in the generated/ subpackage
// (oapi-codegen, regenerated by `make sdk-go` — never hand-edited). This
// top-level package is the handwritten ergonomic layer: api-token auth,
// typed errors (CreditExhaustedError, RateLimitedError, MissingScopeError),
// credit-header accessors, and 429 retry with backoff.
//
// Authenticate with an api token from the Pulsight settings UI, then hand
// the authenticated transport to the generated constructor:
//
//	c := pulsight.New("pk_live_…")
//	api, _ := generated.NewClient(c.BaseURL(),
//		generated.WithHTTPClient(c.HTTPClient()))
//	resp, _ := api.GetTraders(ctx, &generated.GetTradersParams{})
//	// map non-2xx with pulsight.ErrorFromResponse(resp).
//
// See README.md for the full generated-client wiring and submit_and_wait.
package pulsight
